server:
  port: 8902
  tomcat:
    max-http-post-size: 31457280
spring:
  main:
    banner-mode: "off"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 300MB
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost/news-periodical
    username: sq
    password: Sq888
    driverClassName: com.mysql.jdbc.Driver
    poolName: SpringBootHikariCP
    maximumPoolSize: 20
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
    hikari:
      idleTimeout: 10000
      maximumPoolSize: 20
      connection-test-query: SELECT 1
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
  redis:
     host: neikan.shengquan.com
     port: 6379
     password: Sq888
     ssl: false
     database: 1
     jedis:
       pool:
         max-active: 8
         min-idle: 0
         max-idle: 8
management:
  security:
     enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://sq:Sq888@neikan.shengquan.com:8761/eureka/
  instance:
    preferIpAddress: true
    statusPageUrl: http://neikan.shengquan.com:${server.port}/swagger-ui.html
logging:
  level:
    root: info

